
CREATE TABLE public.client_performance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now(),
  monday_id text,
  campaign_name text,
  team_name text,
  sal_status text DEFAULT 'Ongoing',
  output_count bigint DEFAULT 0,
  target_value bigint DEFAULT 0,
  num_influencers bigint DEFAULT 0,
  num_ugc bigint DEFAULT 0,
  company text,
  executed_take_rate_pct numeric DEFAULT 0,
  execution_start date,
  execution_end date,
  views bigint DEFAULT 0,
  engagements bigint DEFAULT 0,
  cpm numeric DEFAULT 0,
  cpe numeric DEFAULT 0,
  er_pct numeric DEFAULT 0
);

ALTER TABLE public.client_performance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read client_performance"
  ON public.client_performance FOR SELECT
  USING (true);

CREATE POLICY "Service role can insert client_performance"
  ON public.client_performance FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Service role can update client_performance"
  ON public.client_performance FOR UPDATE
  USING (true);

CREATE UNIQUE INDEX idx_client_performance_monday_id ON public.client_performance (monday_id);
