
CREATE TABLE public.proposals_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monday_id text UNIQUE,
  campaign_name text,
  company text,
  status text DEFAULT 'To Do',
  budget numeric DEFAULT 0,
  take_rate_pct numeric DEFAULT 0,
  proposal_adjustments integer DEFAULT 0,
  seller_name text,
  csm text,
  list_builder text,
  building_proposal_start date,
  pending_approval_start date,
  days_since_pending integer DEFAULT 0,
  risk_score integer DEFAULT 1,
  ai_insight text,
  action_required text,
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.proposals_audit ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read proposals_audit"
  ON public.proposals_audit FOR SELECT USING (true);

CREATE POLICY "Service role can insert proposals_audit"
  ON public.proposals_audit FOR INSERT WITH CHECK (true);

CREATE POLICY "Service role can update proposals_audit"
  ON public.proposals_audit FOR UPDATE USING (true);
